# Generated by Django 4.2.2 on 2025-03-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager'), ('visitor', 'Visitor')], max_length=20),
        ),
    ]
