# Generated by Django 5.1.5 on 2025-02-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blog_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
