# Generated by Django 5.1.5 on 2025-02-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blog_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
