# Generated by Django 5.1.5 on 2025-02-04 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog_like_num'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('like_num', models.IntegerField(default=0)),
                ('category1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category1', to='core.category')),
                ('category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category2', to='core.category')),
                ('category3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category3', to='core.category')),
                ('category4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category4', to='core.category')),
                ('category5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category5', to='core.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('like_num', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_comment', to=settings.AUTH_USER_MODEL)),
                ('post_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_of_comment', to='core.post')),
            ],
        ),
    ]
