# Generated by Django 5.1.5 on 2025-02-04 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_blog_category1_remove_blog_category2_and_more'),
        ('customer', '0006_alter_favicon_blog_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
