# Generated by Django 4.2.2 on 2025-03-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('baned', 'Baned'), ('okey', 'Okey'), ('auditing', 'Auditing')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='page_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_status', to='core.poststatus'),
        ),
    ]
