# Generated by Django 4.2.2 on 2025-03-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category5',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='core.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_status', to='core.poststatus'),
        ),
    ]
