# Generated by Django 5.1.5 on 2025-01-31 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_blog_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
