# Generated by Django 4.2.2 on 2025-03-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_favicon_blog_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favicon',
        ),
    ]
